### ISSUE TITLE
Tinker's Smeltery Glass

### ISSUE THREAD

**Issue by Gribb13** [heirteir/SpaceCraft#1]
Liquid glass doesn't correctly drain from smeltery into casting basin or table.

**Comment by heirteir** [comment]
I will take a look at this for you. Thank you for bringing this to my attention.

**Comment by heirteir** [comment]
Are you sure you set up the smeltery correctly? I was able to cast liquid glass into a basin. Could you send a screenshot of your smeltery setup?

**Comment by Gribb13** [comment]
![image](https://user-images.githubusercontent.com/42370542/44083366-b136ca68-9fab-11e8-8679-fd5584b55743.png)

**Comment by Gribb13** [comment]
Sorry for the multiscreen :P

**Comment by Gribb13** [comment]
For clarity, everything else I've tried casts just fine, only glass I've found to be a problem.  Done after melting sand into smeltery.

**Comment by heirteir** [comment]
Hmm, I will be releasing an update today. If it still occurs after the update post in the issue again, and I will take a deeper look. The only thing I can guess is that I somehow fixed it in my version without knowing it.

**Comment by Gribb13** [comment]
No need to apologise, the pack is looking really good, and not being able to cast glass is a pretty tiny issue overall ;)

**Comment by heirteir** [comment]
Thanks :)
